allow for reading until EOF with the function ParseUntilEOF
suyashkumar/dicom pull request #270
Opened 2023-04-13 13:48 UTC by amitbet

This fix allows reading until EOF, without providing "bytesToRead", it keeps the previous Parse signature for backwards compatibility and creates a new ParseUntilEOF function which doesn't require the extra param.

This addresses #236.

2023-04-20 01:28 UTC, suyashkumar requested changes
Thanks for the contribution! Could you please tag issue #236 in your description and update the imports and links to point to this repo so that we can run the automated tests as well? Thank you!

2023-04-20 01:28 UTC, suyashkumar commented on README.md
> +    <a href="https://github.com/amitbet/dicom/actions"><img src="https://github.com/amitbet/dicom/workflows/build/badge.svg" /></a>
can you please restore the links in the README to this repo, including the imports so that the automated tests can run? Thanks!

2023-04-20 01:28 UTC, suyashkumar commented on parse.go
> +			if err.Error() == "EOF" {
```suggestion
			if errors.Is(err, io.EOF) {
```

I think you should be able to do the above.

2023-04-24 20:46 UTC, amitbet commented
I will create a new PR from a cleaner branch (i thought that i can PR main and then do some changes  - turns out the PR  tracks the new changes on the branch)

2023-04-25 01:10 UTC, suyashkumar commented
Closing as @amitbet opened #273 to superseed this one!

2023-04-25 01:10 UTC, closed without merging